import json

with open('final_terrain.json') as f:
    data = json.load(f)
terrain = data['terrain']      # {"q,r": terrain}
rivers = data['rivers']        # [[[q1,r1],[q2,r2]], ...]

def edge_key(a, b):
    a = tuple(a); b = tuple(b)
    lo, hi = sorted([a, b])
    return f"{lo[0]},{lo[1]}|{hi[0]},{hi[1]}"

# recompute named-zone anchors in axial from offset (approx, for naval flavor)
def off_to_axial(col, row):
    return col, row - (col - (col & 1)) // 2

lines = []
lines.append("// Auto-generated by tools/map-extract from the scanned Heraklios board")
lines.append("// (Jeux & Stratégie #6, 1980). Coordinates are axial (q, r) for flat-top")
lines.append("// hexes. Terrain is per-hex; rivers are HEXSIDE features stored as the")
lines.append("// set of undirected edges between adjacent hexes they run along.")
lines.append("import type { TerrainType } from './terrain';")
lines.append("")
lines.append("export interface HexCoord {")
lines.append("  q: number;")
lines.append("  r: number;")
lines.append("}")
lines.append("")
lines.append("export function hexKey(q: number, r: number): string {")
lines.append("  return `${q},${r}`;")
lines.append("}")
lines.append("")
lines.append("/** Canonical undirected key for the hexside between two adjacent hexes. */")
lines.append("export function riverEdgeKey(a: HexCoord, b: HexCoord): string {")
lines.append("  const lo = a.q < b.q || (a.q === b.q && a.r <= b.r) ? a : b;")
lines.append("  const hi = lo === a ? b : a;")
lines.append("  return `${lo.q},${lo.r}|${hi.q},${hi.r}`;")
lines.append("}")
lines.append("")
lines.append("export const MAP_TERRAIN: ReadonlyMap<string, TerrainType> = new Map([")
for key in sorted(terrain, key=lambda k: tuple(map(int, k.split(',')))):
    lines.append(f"  ['{key}', '{terrain[key]}'],")
lines.append("]);")
lines.append("")
lines.append("/** Hexsides that carry a (normal) river. Membership is symmetric. */")
lines.append("export const RIVER_HEXSIDES: ReadonlySet<string> = new Set([")
seen = set()
for (a, b) in rivers:
    k = edge_key(a, b)
    if k in seen:
        continue
    seen.add(k)
    lines.append(f"  '{k}',")
lines.append("]);")
lines.append("")
lines.append("export const NAMED_ZONES = {")
lines.append("  ansedHypnos: { q: 16, r: 3 },")
lines.append("  pointeDEole: { q: 18, r: 9 },")
lines.append("  baieDArgos: { q: 22, r: -2 },")
lines.append("  capZenon: { q: 27, r: 3 },")
lines.append("} as const;")
lines.append("")

with open('map_v2.ts', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print("wrote map_v2.ts:", len(terrain), "hexes,", len(seen), "river hexsides")
