// ESLint flat config. Two layers:
//
// 1. Correctness rules (eslint + typescript-eslint recommended) — errors.
// 2. Agent guardrails from the AI coding guidelines (file length, function
//    length, complexity, parameter count) — warnings, because existing files
//    such as BoardScene.ts predate them. `npm run lint` caps the warning
//    count at the current baseline (see package.json), so new violations
//    fail `npm run verify` while the old ones are paid down. The cap counts
//    warnings, not locations — when you remove warnings, lower the cap in
//    the same commit, or a later change can quietly spend the slack.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      'dist/',
      'node_modules/',
      '.claude/',
      '.codex/',
      'tools/map-extract/',
      '**/*.tsbuildinfo',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // Guardrails (AI Coding & Agent Usage Guidelines §1.8).
      'max-lines': ['warn', { max: 500, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['warn', { max: 80, skipBlankLines: true, skipComments: true }],
      complexity: ['warn', 20],
      'max-params': ['warn', 7],
      'max-depth': ['warn', 4],
      // Guidelines: no raw console writes outside deliberate, annotated spots.
      'no-console': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Tests are long `describe` blocks by nature; the function-length and
    // file-length guardrails measure nothing useful there.
    files: ['**/*.test.ts', '**/*.test.mjs'],
    rules: {
      'max-lines': 'off',
      'max-lines-per-function': 'off',
    },
  },
  {
    // CLI scripts report on stdout; printing is their job.
    files: ['scripts/**'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    // Generated by the map editor / tools/map-extract — not hand-written.
    files: ['src/data/map.ts'],
    rules: {
      'max-lines': 'off',
    },
  },
);
